# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Pluggable
version:      0.01
version_from: lib/CGI/Application/Pluggable.pm
installdirs:  site
requires:
    CGI::Application:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
